// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAG8s1KEOCt_AI4cmzwAn7_fb8pTOGYgFw',
    appId: '1:1049693755732:android:af982b7f19af73062e50c1',
    messagingSenderId: '1049693755732',
    projectId: 'kitahack-f5f7d',
    databaseURL: 'https://kitahack-f5f7d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'kitahack-f5f7d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJ_IrN0b0vEs2RfQOe6EhVGyFpgqFABxE',
    appId: '1:1049693755732:ios:f975252153e176922e50c1',
    messagingSenderId: '1049693755732',
    projectId: 'kitahack-f5f7d',
    databaseURL: 'https://kitahack-f5f7d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'kitahack-f5f7d.firebasestorage.app',
    iosBundleId: 'com.example.kitahack',
  );
}
